name: Jalur Otomatisasi Deploy ke RHEL

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-server:
    runs-on: self-hosted  # Menggunakan runner lokal di RHEL

    steps:
    - name: 1. Ambil Kode Terbaru dari GitHub
      uses: actions/checkout@v4

    - name: 2. Bangun dan Jalankan Kontainer Docker
      run: |
        # Menggunakan file yang sudah ditarik oleh aksi checkout di atas
        docker build -t web-cicd-app .
        
        # Hentikan dan hapus kontainer lama jika sedang berjalan
        docker stop web-cicd-container || true
        docker rm web-cicd-container || true
        
        # Jalankan kontainer baru di port 8081
        docker run -d --name web-cicd-container -p 8081:80 --restart always web-cicd-app
